all: Bigram.class BigramDyn.class myPair.class _mainTester.class BigramMap.class

Bigram.class: Bigram.java
	javac -g Bigram.java

BigramDyn.class: BigramDyn.java
	javac -g BigramDyn.java

myPair.class: myPair.java
	javac -g myPair.java

BigramMap.class: BigramMap.java
	javac -g BigramMap.java

_mainTester.class: _mainTester.java
	javac -g _mainTester.java
	
clean:
	rm *.class 
